"""empty message

Revision ID: 719611ed2423
Revises: c5ca1f3b0f1c
Create Date: 2021-01-01 21:12:41.464088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719611ed2423'
down_revision = 'c5ca1f3b0f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('title', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'title')
    # ### end Alembic commands ###
